"""Centralised API configuration manager for MiniMaxRefDirector.

Stores provider base URLs, API keys, and default LLM/VLM model selections in
ComfyUI's user directory. Used by both the backend API calls and the frontend
Settings panel.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import folder_paths


DEFAULT_CONFIG = {
    "services": [
        {
            "id": "glm",
            "name": "智谱 GLM",
            "base_url": "https://open.bigmodel.cn/api/paas/v4/chat/completions",
            "api_key": "",
            "llm_models": ["glm-4-flash-250414", "glm-4.5-flash", "glm-4-plus"],
            "vlm_models": ["glm-4v-flash", "glm-4.6V-Flash"],
        },
        {
            "id": "kimi",
            "name": "Kimi (Moonshot)",
            "base_url": "https://api.moonshot.cn/v1/chat/completions",
            "api_key": "",
            "llm_models": ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
            "vlm_models": ["moonshot-v1-8k-vision-preview"],
        },
        {
            "id": "qwen",
            "name": "通义千问 (Qwen)",
            "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
            "api_key": "",
            "llm_models": ["qwen-turbo", "qwen-plus", "qwen-max"],
            "vlm_models": ["qwen-vl-plus", "qwen-vl-max"],
        },
        {
            "id": "doubao",
            "name": "豆包 (Doubao / 火山引擎)",
            "base_url": "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
            "api_key": "",
            "llm_models": ["doubao-lite-4k", "doubao-pro-4k"],
            "vlm_models": ["doubao-vision-lite-4k", "doubao-vision-pro-4k"],
        },
        {
            "id": "xflow",
            "name": "xFlow API聚合",
            "base_url": "https://api.xflow.cc/v1/chat/completions",
            "api_key": "",
            "llm_models": ["gpt-4o-mini", "claude-3-haiku"],
            "vlm_models": ["gpt-4o", "claude-3-5-sonnet-20241022"],
        },
        {
            "id": "ollama",
            "name": "Ollama (本地)",
            "base_url": "http://localhost:11434/v1/chat/completions",
            "api_key": "ollama",
            "llm_models": [],
            "vlm_models": [],
        },
    ],
    "current": {
        "llm": {"service": "glm", "model": "glm-4.5-flash"},
        "vlm": {"service": "glm", "model": "glm-4v-flash"},
    },
}


def _config_dir() -> Path:
    user_dir = Path(folder_paths.get_user_directory())
    cfg_dir = user_dir / "default" / "MiniMaxRefDirector"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    return cfg_dir


def _config_path() -> Path:
    return _config_dir() / "api_config.json"


# Legacy display names for the built-in providers. Kept so that workflows saved
# with the old fixed combo values ("GLM", "Kimi", "Qwen", "Doubao") keep working.
_LEGACY_PROVIDER_NAMES = {
    "glm": "GLM",
    "kimi": "Kimi",
    "qwen": "Qwen",
    "doubao": "Doubao",
}


def provider_label(service: dict) -> str:
    """Build the api_provider combo label for a configured service.

    Built-in services keep their legacy names so old workflows stay compatible;
    other services (xflow, ollama, user-added) are shown as "name (id)".
    """
    sid = (service.get("id") or "").strip()
    if not sid:
        return ""
    if sid in _LEGACY_PROVIDER_NAMES:
        return _LEGACY_PROVIDER_NAMES[sid]
    name = (service.get("name") or "").strip()
    if name and name.lower() != sid.lower():
        return f"{name} ({sid})"
    return sid


def parse_provider_value(provider: str) -> str:
    """Map an api_provider combo value back to a config service id.

    Accepts legacy names ("GLM"), bare ids ("xflow", "ollama") and labeled
    values ("name (id)") generated by provider_label().
    Returns "" when nothing usable is found.
    """
    p = (provider or "").strip()
    if not p:
        return ""
    m = re.match(r"^.*\(([^()]+)\)$", p)
    if m:
        return m.group(1).strip().lower()
    return p.lower()


class APIConfigManager:
    """Load / save / query the provider & model configuration."""

    def __init__(self) -> None:
        self._config_path = _config_path()

    def load_config(self) -> dict:
        """Return the saved config, creating defaults if none exists."""
        if self._config_path.exists():
            try:
                with open(self._config_path, "r", encoding="utf-8") as f:
                    loaded = json.load(f)
                # Merge missing default services / current entries.
                return self._merge_defaults(loaded)
            except (json.JSONDecodeError, OSError):
                pass
        return json.loads(json.dumps(DEFAULT_CONFIG))

    def save_config(self, config: dict) -> None:
        """Persist the full config to disk."""
        with open(self._config_path, "w", encoding="utf-8") as f:
            json.dump(config, f, ensure_ascii=False, indent=2)

    def _merge_defaults(self, config: dict) -> dict:
        """Ensure the config contains every default service and current keys."""
        config = config or {}
        services = {s["id"]: s for s in config.get("services", [])}
        default_services = {s["id"]: s for s in DEFAULT_CONFIG["services"]}

        merged_services = []
        for sid, default_svc in default_services.items():
            user_svc = services.get(sid, {})
            merged = {
                **default_svc,
                **{k: v for k, v in user_svc.items() if k != "id"},
                "id": sid,
            }
            # Preserve user-added models if any.
            for mode in ("llm_models", "vlm_models"):
                user_models = list(user_svc.get(mode, []))
                default_models = list(default_svc.get(mode, []))
                if user_models:
                    merged[mode] = user_models
                else:
                    merged[mode] = default_models
            merged_services.append(merged)

        # Append any completely custom user services at the end.
        known_ids = set(default_services)
        for svc in config.get("services", []):
            if svc.get("id") not in known_ids:
                merged_services.append(svc)

        current = config.get("current", {})
        default_current = DEFAULT_CONFIG["current"]
        merged_current = {
            "llm": {**default_current["llm"], **current.get("llm", {})},
            "vlm": {**default_current["vlm"], **current.get("vlm", {})},
        }

        return {"services": merged_services, "current": merged_current}

    def get_service(self, service_id: str) -> dict | None:
        """Return a service dict by id, or None if not found."""
        for svc in self.load_config().get("services", []):
            if svc.get("id") == service_id:
                return svc
        return None

    def get_active_config(self, mode: str = "vlm") -> dict:
        """Return the currently selected {service_id, service_name, model, base_url, api_key}."""
        mode = "llm" if mode == "llm" else "vlm"
        cfg = self.load_config()
        current = cfg.get("current", {}).get(mode, {})
        service_id = current.get("service", "")
        model = current.get("model", "")
        service = self.get_service(service_id)
        if service is None:
            service = cfg.get("services", [{}])[0] or {}
            service_id = service.get("id", "")
        if not model:
            models = service.get(f"{mode}_models", []) or []
            model = models[0] if models else ""
        return {
            "service_id": service_id,
            "service_name": service.get("name", service_id),
            "model": model,
            "base_url": service.get("base_url", ""),
            "api_key": service.get("api_key", ""),
        }

    def get_config_for(self, mode: str = "vlm", service_id: str | None = None) -> dict:
        """Return config for a specific service; fall back to the active config."""
        mode = "llm" if mode == "llm" else "vlm"
        if service_id:
            service = self.get_service(service_id)
            if service is not None:
                cfg = self.load_config()
                current = cfg.get("current", {}).get(mode, {})
                model = ""
                if current.get("service") == service_id:
                    model = current.get("model", "")
                if not model:
                    models = service.get(f"{mode}_models", []) or []
                    model = models[0] if models else ""
                return {
                    "service_id": service_id,
                    "service_name": service.get("name", service_id),
                    "model": model,
                    "base_url": service.get("base_url", ""),
                    "api_key": service.get("api_key", ""),
                }
        return self.get_active_config(mode)

    def get_provider_options(self, mode: str = "vlm") -> tuple[list[str], str]:
        """Return (options, default) for the nodes' api_provider combo.

        options contains one entry per configured service (built-ins use their
        legacy names so old workflows stay compatible, custom services show as
        "name (id)"); default is the label of the active service for `mode`.
        Falls back to the legacy fixed list on any error.
        """
        mode = "llm" if mode == "llm" else "vlm"
        fallback = (["GLM", "Kimi", "Qwen", "Doubao"], "GLM")
        try:
            cfg = self.load_config()
            services = cfg.get("services", [])
            options = [provider_label(s) for s in services if (s.get("id") or "").strip()]
            if not options:
                return fallback
            active_id = cfg.get("current", {}).get(mode, {}).get("service", "")
            default = ""
            if active_id:
                for s in services:
                    if s.get("id") == active_id:
                        default = provider_label(s)
                        break
            if not default:
                default = options[0]
            return options, default
        except Exception:
            return fallback


api_config_manager = APIConfigManager()
